#!/bin/bash
# Setup 3-Laptop Distributed SDN System

echo "=========================================="
echo "3-Laptop Distributed SDN Setup"
echo "=========================================="

# Install required packages
echo "[1] Installing packages..."
pip install flask 2>&1 | tail -3

echo ""
echo "=========================================="
echo "SETUP COMPLETE"
echo "=========================================="
echo ""
echo "THREE LAPTOPS SETUP:"
echo ""
echo "LAPTOP 1 (SDN Controller):"
echo "  python3 sdn_controller.py"
echo "  Listens on: 192.168.1.100:9000"
echo ""
echo "LAPTOP 2 (AP Agent):"
echo "  python3 ap_agent.py"
echo "  Sends to: 192.168.1.100:9000"
echo "  Listens on: 192.168.1.101:9001"
echo ""
echo "LAPTOP 3 (Monitor & Jammer Agent):"
echo "  python3 monitor_agent.py"
echo "  Sends to: 192.168.1.100:9000"
echo ""
echo "DASHBOARD (Any laptop):"
echo "  python3 dashboard.py"
echo "  Open: http://localhost:5000"
echo ""
echo "=========================================="
echo ""
echo "NETWORK REQUIREMENTS:"
echo "  - All laptops on same network"
echo "  - Laptop 1 IP: 192.168.1.100"
echo "  - Laptop 2 IP: 192.168.1.101"
echo "  - Laptop 3 IP: 192.168.1.102 (or any)"
echo ""
echo "ADJUST IPs IN CODE IF DIFFERENT!"
echo "=========================================="
